[workspace.package]
version = "0.1.0"
description = "A new kind of Shell"
license = "Apache-2.0"

[workspace]
members = ["neosh"]
resolver = "3"

[workspace.dependencies]
mimalloc = { version = "0.1.48", features = ["v3", "override"] }
