[package]
name = "neosh-libc"
edition = "2024"
version.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
libc = { workspace = true }

getset = { workspace = true }
typed-builder = { workspace = true }